### ISSUE TITLE
Delete Gloss via API

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1210]
We should be able to delete Gloss via API with using Gloss ID, with confirm callback. 

signCollect ask Signbank to delete Gloss. 
Signbank replies: Gloss is found, are you sure? 
signCollect will confirm the deletion. 
Signbank callbacks with gloss deleted. 

signCollect will keep seperate backup for that gloss in event of user error and then it can re-create the gloss.

**Comment by susanodd** [comment]
This is extremely dangerous!
It's an object-oriented database.
There is no "undo".
A delete also deletes all relations the gloss is part of as well as the videos.
This could affect glosses in the corpus that other users have made. There are no gloss-specific permissions.

**Comment by rem0g** [comment]
We are able to delete glosses via Signbank Website, why wouldnt that be possible via API?

**Comment by susanodd** [comment]
> We are able to delete glosses via Signbank Website, why wouldnt that be possible via API?

Because there are no humans involved and you want to automate it.

**Comment by rem0g** [comment]
Please limit your responses to software developement, if you want to discuss about this then i would suggest to mail or make an appointment with me and Ulrika. This feature is needed unfortunately as our colleagues can make mistakes sometimes.

**Comment by Woseseltops** [comment]
Hey @rem0g, I (and Jetske too) do agree this feature would be a valuable addition to the API. I think Susan intended to point out that with automated systems, the risk of accidental deletion of large amounts of glosses could be higher. This is something we can fix at our side:

1. Have an extra gloss field `archivedAtDate`. If this field is set, the gloss won't show up in any lists, searches, API output, etc
2. Have a cronjob that after every x time units, deletes all glosses with an `archivedAtDate` that is older than y days ago.

**Comment by rem0g** [comment]
Ok perfect, that is something i can work with.

**Comment by susanodd** [comment]
See #1211

**Comment by susanodd** [comment]
Do you need different "corpus gloss ID"s for your glosses?

The CNGT glosses should not be deleted because all the frequency data from the EAF files depends on them.
The Signbank ID is that used in the CNGT also.

Do glosses need an additional UvA ID field?

The Gloss ID (Signbank ID) is also linked to a Corpus via a table. Also to Document, Speaker, Frequency objects.
(These are visible in the Gloss Frequency panel of the Gloss View.)
Because these IDs are used by researchers, they should not be deleted.

Do you require "different" IDs for the glosses in your corpus?
A gloss may be associated with more than one corpus.
But the ID cannot be changed.

So probably we can add an additional UvA ID field. Or another table to map glosses that appear in mutliple corpora to Gloss IDs in the various corpora. Then they could be looked up via either.
Then the Affiliation could be added to the API routines.

The CNGT glosses should not be deleted. The frequency routines run as a cron job that updates based on updates to the EAF files for CNGT.

**Comment by susanodd** [comment]
The minimal pairs are also computed dynamically. (Not stored anywhere.)

I don't know enough about Phonology itself to know whether you would be using completely different field choices in your software. If so, that would cause problems for researchers making use of the minimal pairs if you start updating the phonology of CNGT glosses. Or delete glosses that are in the minimal pairs of a CNGT gloss.

**Comment by susanodd** [comment]
Please check out #127.

Deleting a gloss also deletes the relations and morphology.
Changing the annotation to add a suffix would be preferred.

**Comment by Woseseltops** [comment]
Not sure if I fully understand you, but I don't really see the problem. Let's do this in phases:

* Phase 1: refactor so the existing `delete gloss` functionality does not actually delete things anymore, but just switches the boolean on a new `archived` field. Good point that this isn't just the case for glosses, but also for the other things (relations) that are deleted in the `delegate gloss` functionality.
* Phase 2: make sure that in all situations where objects with an `archived` field are requested, you filter out the objects with `archived=False`.
* Phase 3: add the API endpoint

**Comment by susanodd** [comment]
Okay, nice, that's wise to do it that way. Then we can make sure everything still works with the new archived field!

**Comment by rem0g** [comment]
Bump. Any updates?

**Comment by susanodd** [comment]
This has been on the back burner because we had to get the API token working before other things.

**Comment by rem0g** [comment]
And now? We should solve this issue asap, really frustrating as i see other tasks are being executed but this doesnt.

**Comment by susanodd** [comment]
I've got as far as I can tell all the queries over Gloss to exclude those with archived set to True.

I added a new post_save method that when the archived is set to True (which replaces the previous "delete()" so the archived gloss is saved to the DeletedGlossOrMedia, as before and can be seen in the Admin.

Now after the archived has been set to True, as part of this post_save method, the following needs to be done:

```
def cascade_archival_gloss(gloss):

    relations_source = Relation.objects.filter(source=gloss)
    relations_target = Relation.objects.filter(target=gloss)
    morphemes_parent = MorphologyDefinition.objects.filter(parent_gloss=gloss)
    morphemes_appears_in = MorphologyDefinition.objects.filter(morpheme=gloss)
    simultaneous = SimultaneousMorphologyDefinition.objects.filter(parent_gloss=gloss)
    blends = BlendMorphology.objects.filter(parent_gloss=gloss)
    partofblends = BlendMorphology.objects.filter(glosses=gloss)

    # delete all of the relation objects above when the gloss is archived
```

This will effectively detach/remove the archived gloss from all the tables/other models that reference it.

**Comment by susanodd** [comment]
Important to implementation:

Do you wish to be able to "undo" a previous delete?

To make this possible, so the dataset manager has control over when an archived gloss can be removed, I'll adjust the related object (querying) shown above so that references to archived glosses are ignored.

What is potentially an issue is if you wish to "delete" a gloss and then make use of the exact same annotation/lemma text fields.
For example, you have a GLOSS-A and then delete/archive GLOSS-A. And then you want to make another GLOSS-A.

(That seems kind of messed up, why not just "repair" the original GLOSS-A ?)

This may seem trivial, but the archived glosses will still interfere with the constraints for creating new glosses.
You wouldn't be able to "undo" a previously archived gloss if its annotations are reused for other glosses, because the "undo" would fail because all of a sudden there would be constraint violations introduced.

**Comment by susanodd** [comment]
I just need to add an API command now.

The archived glosses are made invisible in all the other queries of glosses and related objects queries.

The code in general still works, so I didn't break anything.

If something is missing, then the archived gloss could still show up.

I did not do anything about its videos. They will still be stored in the file system.
And the annotation and lemma fields will still cause constraint violations if attempted to be used again.
(I don't think this can be done otherwise because a constraint is a constraint.)


@vanlummelhuizen updates to the API urls has been merged. #1278 
That has been deployed on all servers except signbank-jetske and signbank-dev

**Comment by susanodd** [comment]
This is on signbank-dev now.

The Gloss Edit DELETE now archives the gloss. (This can be tested out.)

As far as I know the gloss should not be visible anymore in queries and relations.
(If you find a deleted gloss referenced, then kindly report a bug. Then I missed something.)

I'm working on the API url now.

**Comment by susanodd** [comment]
> We should be able to delete Gloss via API with using Gloss ID, with confirm callback.
> 
> signCollect ask Signbank to delete Gloss. Signbank replies: Gloss is found, are you sure? signCollect will confirm the deletion. Signbank callbacks with gloss deleted.
> 
> signCollect will keep seperate backup for that gloss in event of user error and then it can re-create the gloss.

Okay, I'm up to the actual API URL now.
I've implemented the "archived" field and all the other necessary functionality to support it.
Now it only needs to be set to True.

I've got the url method nearly done. But I realised there ought to be some kind of POST data to it,
perhaps just confirm as a json field?

This to distinguish it from just being a url anybody can type in.
It has permission checks of course, but it seems onwenselijk if users can just type in a url.

**Comment by susanodd** [comment]
I implemented:

`api_delete_gloss/<datasetid>/<glossid>/`

`api_restore_gloss/<datasetid>/<glossid>/`

Both expect json data:

`{ 'confirmed':  'True' }`

**Comment by susanodd** [comment]
This is deployed on signbank now.

**Comment by rem0g** [comment]
Wiki needs be updated with instructions how to use glos delete.

**Comment by susanodd** [comment]
Added to wiki.
