### ISSUE TITLE
Remove dataset_choices

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#414]
This code on adminviews.py was causing problems for the Americans, as they have no dataset permissions set. 

```python
        context['dataset_choices'] = {}
        user = self.request.user
        if user.is_authenticated():
            qs = get_objects_for_user(user, 'view_dataset', Dataset)
            dataset_choices = {}
            for dataset in qs:
                dataset_choices[dataset.name] = dataset.name
            context['dataset_choices'] = json.dumps(dataset_choices)
```

Figure out if this can be removed (@vanlummelhuizen says it's not used anymore), and remove if so.

**Comment by susanodd** [comment]
It's used in gloss_edit.js.
It's used in morpheme_detail and gloss_detail by the class "edit edit_dataset".

**Comment by susanodd** [comment]
I made the code in adminviews and in morpheme_detail dependent on whether SHOW_DATASET_INTERFACE_OPTIONS is set.

**Comment by Woseseltops** [comment]
Thanks, @susanodd !

> dependent on whether SHOW_DATASET_INTERFACE_OPTIONS is set.

But the Americans do actually have that setting, but it's False. How about:

```python
if hasattr(settings, 'SHOW_DATASET_INTERFACE_OPTIONS') and settings.SHOW_DATASET_INTERFACE_OPTIONS:
```

And as the scope of the ```SHOW_DATASET_INTERFACE_OPTIONS``` is growing, maybe we should rename it?

**Comment by Woseseltops** [comment]
Note to self: this code is currently commented out in the ASL detail view.

**Comment by Woseseltops** [comment]
Kind reminder @susanodd , this issue still has an open question for you.

**Comment by susanodd** [comment]
I'm not exactly sure which part hasn't been done yet, @Woseseltops .
The code is needed for the javascript that displays the pull-down menu's.
The variable (with the same name) SHOW_DATASET_INTERFACE_OPTIONS) is used in the templates.
This context variable with the same name as the system setting was introduced in order to pass the data to the template.
The code that sets up the dataset_choices variable in the context is prefaced as you show above, it checks whether settings.SHOW_DATASET_INTERFACE_OPTIONS is set.
The template in turn also checks the (context) variable SHOW_DATASET_INTERFACE_OPTIONS before using the dataset_choices.

I can't see any other open question (?) You mean rename it?

**Comment by susanodd** [comment]
Ahha! Shall I remove all the tests for the existance of the setting?

**Comment by vanlummelhuizen** [comment]
So, @susanodd made a change that should solve this: 5c8022151d3841eaec3cb73f93ff10152866ab1b. This commit did not end up here because there was no issue reference in the message. 

@Woseseltops as far as I am concerned, the name of the setting is OK. But perhaps I am overlooking something.

**Comment by Woseseltops** [comment]
> So, @susanodd made a change that should solve this: 5c80221.

Aha I see. And, interestingly, she did so 2 days BEFORE my reminder.

![](https://i.imgur.com/7UJQcLe.gif)

>  the name of the setting is OK

I think my original reasoning was that we were no longer exclusively using the option for (de)activating dataset things IN THE INTERFACE - this issue is more about deactivating dataset functionality in general so we don't get errors. On other hand, these errors still show up in the interface, so let's leave things like they are for now :).
