### ISSUE TITLE
Cron job for ECV shows errors

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#591]
of the type: get_ecv_descripion_for_gloss error getting field_choice_category, set to empty list. Check models.py for choice list declarations.

**Comment by susanodd** [comment]
Hmm. I recognise that's my type error print statement.
It looks like I didn't know where to put the ECV settings in the new "default" versus "server_specific" configuration.
This has been fixed and pushed to github.

**Comment by vanlummelhuizen** [comment]
It is on the live server.

**Comment by ocrasborn** [comment]
Hi @vanlummelhuizen: Not sure whether this was solved for some time, but I noticed yesterday  I'm still getting the errors in the log email.

**Comment by vanlummelhuizen** [comment]
Hi @ocrasborn this should be fixed according to a small test on the TestDatasetMicha. Please confirm tomorrow morning.

@susanodd please look at https://github.com/Signbank/Global-signbank/commit/1ecd165e601ccdde84c3a283595564c6384444a0 for it solves a problem in what I believe is your code.

**Comment by susanodd** [comment]
Yykes! That looks like sloppy copy paste on my part.

**Comment by susanodd** [comment]
I modified a similar code construct (list comprehension inside of try except) in models.py.
The method generate_frequency_dict. We don't have an issue so I just tagged it to this issue.

(Issue is list comprehension inside of try except. We want to skip things rather than make an exception for the entire result. That's not really a Signbank issue, but a programming style.)

**Comment by susanodd** [comment]
@vanlummelhuizen, just to point out, for fields of a Gloss, "field.choices" does not give an error, it just returns [] for non-existent choice lists. This can be confirmed in the tests for FieldChoiceTests and a simple print statement in the function fields_with_choices_glosses in tools.py, which iterates over all fields in Gloss._meta.fields.

**Comment by susanodd** [comment]
The exceptions were intended to alert the administrator that fields with choices that don't have the field_choice_category field are missing this. This is still don't in the fields_with_choices_glosses function in tools.py. Because this function is used in the tests, it should expose such a situation during testing.

**Comment by susanodd** [comment]
This should all be working now.

**Comment by ocrasborn** [comment]
Nope, going well now @vanlummelhuizen

**Comment by vanlummelhuizen** [comment]
Good. Closing the issue.
