### ISSUE TITLE
Uploading videos truncates the video

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#911]
I tried using this feature and I signed a test sign twice but the video cut off after 1 sec

_Originally posted by @rosestamp in https://github.com/Signbank/Global-signbank/issues/266#issuecomment-1464213011_

**Comment by susanodd** [comment]
This happens with all video uploads.

It doesn't happen with Other Media uploads.

**Comment by susanodd** [comment]
The other media model uses a `CharField` type for the `path`:
https://github.com/Signbank/Global-signbank/blob/ea4378edef1818f0eb7919eb0da8d0ce3bca6005/signbank/dictionary/models.py#L2308-L2317
whereas the GlossVideo uses Django FileField
https://github.com/Signbank/Global-signbank/blob/ea4378edef1818f0eb7919eb0da8d0ce3bca6005/signbank/video/models.py#L208-L219
which in turn uses:
https://github.com/Signbank/Global-signbank/blob/ea4378edef1818f0eb7919eb0da8d0ce3bca6005/signbank/video/models.py#L98-L102
where the setting is:
https://github.com/Signbank/Global-signbank/blob/ea4378edef1818f0eb7919eb0da8d0ce3bca6005/signbank/settings/base.py#L24
(But this is actually wrong.)

**Comment by susanodd** [comment]
We could define a new model field path for GlossVideo and store the actual path rather than let Django do it. (Using a simple migration to just copy the existing paths from the FileFields.)

Or this really old issue: #320.

This is probably related to large video files because they aren't finished being uploaded when the FileField needs to be stored in GlossVideo.

**Comment by Jetske** [comment]
I tried some more videos and the cutoff seems to happen in convert_to_mp4 so I switched that off for uploads and am working on another solution for recordings..

**Comment by susanodd** [comment]
I deployed your changes, @Jetske.
It's back to normal for the normal uploading.

**Comment by susanodd** [comment]
I had this comment in the pull request:

> I'm getting the conversion error on my local PyCharm server now.
> But because the convert video uses "stderr" the actual message can't be captured in the except clause, so it's not possible to see what the error is. It's also not possible to determine an appropriate exception type for the try except clause.

Perhaps that's why we can't catch the errors to take appropriate action. It seems the exception is from inside the ffmpeg python module and that is printing it to stderr. Maybe the newest version will solve this with the Django and Python bumps?

**Comment by susanodd** [comment]
On running the command (in the virtual environment, with a call to convert_video when a non-mp4 is found):

```

> Non-MP4 video file found:  /home/susan/signbank/writable/glossvideo/NGT/GE/GEHOORAPPARAAT-D-3092.mp4 video/quicktime
> File copied to:  /home/susan/signbank/writable/video_backups/GEHOORAPPARAAT-D-3092-conv.mp4
> /home/susan/signbank/writable/glossvideo/NGT/GE/GEHOORAPPARAAT-D-3092.mp4
> Conversion to mp4 failed:  /home/susan/signbank/writable/glossvideo/NGT/GE/GEHOORAPPARAAT-D-3092.mp4
> ffmpeg error (see stderr output for detail)

```

**Comment by Jetske** [comment]
@susanodd I switched some things around and found an older conversion function that also works for recorded videos so I _hope_ it works better this way. Still no luck for recording in firefox, though (and I don't know about safari/apple), but it seems that videos recorded in other browsers can at least be played in firefox.

**Comment by susanodd** [comment]
@Jetske this has been deployed.

**Comment by Jetske** [comment]
Ok, looks like the truncating doesn't happen anymore. I also replaced the use of convert_to_mp4 in create_small_videos.py with the better working conversion.

**Comment by susanodd** [comment]
I merged it, and tried to deploy it, but the tests fail on `ensure_mp4` when it tries this:
[ ed: I removed the first part of the paths so just the relevant part ]

```

-   File "      signbank/dictionary/tests.py", line 3528, in setUpTestData
-     test_gloss_video.save()
-   File "     signbank/video/models.py", line 222, in save
-     self.ensure_mp4()
-   File "     signbank/video/models.py", line 277, in ensure_mp4
-     os.remove(oldloc)
- FileNotFoundError: [Errno 2] No such file or directory: '   writable/test_video_url_in_gloss_api_tests'

```

**Comment by susanodd** [comment]
In the above, in ensure_mp4

https://github.com/Signbank/Global-signbank/blob/dfb48721f5597da554a18ea9cef093cad413dd62/signbank/video/models.py#L79

print of the err returned yields False in the above.

**Comment by susanodd** [comment]
@Jetske can you maybe undo that last change?

**Comment by susanodd** [comment]
From the old function `convert_to_mp4` (that was removed) this code was used:

```
        import ffmpeg
        ffmpeg.input(self.videofile.path).output(out_name).run(quiet=True, overwrite_output=True)
```

That had the effect of "converting the original file" that was in GlossVideo's videofile (`overwrite_output`)
The test creates a temporary video that is deleted after the test.
Perhaps leave the original function there rather than delete it.

**Comment by Jetske** [comment]
Okay, there it is

**Comment by susanodd** [comment]
@Jetske did something happen to the specific conversion?
It used to convert files to H264, because that works on Apple.
The command to convert non-mp4 videos of other media isn't converting them to that format anymore.
(It's using the same convert_video that used to work.)

**Comment by susanodd** [comment]
@vanlummelhuizen why is this in a try except?

https://github.com/Signbank/Global-signbank/blob/f82960bdd3f6b5a9047e1d6443822add9af80082/signbank/video/convertvideo.py#L3-L10

For Apple, the H264 is needed.

**Comment by susanodd** [comment]
@vanlummelhuizen we're having trouble debugging the videos because it works on our local computers, but not on Global. So we can't duplicate the errors locally.

**Comment by Jetske** [comment]
@susanodd I don't think something happened to the specific conversion

In the try it uses settings.FFMPEG_OPTIONS which is ["-vcodec", "h264", "-an"] so that is also H264, except that it uses ffmpeg instead of avconv

**Comment by susanodd** [comment]
Because that's inside of a try-except, I suspect it's getting ignored on Global.

**Comment by Jetske** [comment]
When I tried again, that version made the server crash when used in Firefox and it made a truncated video that was also slowed-down a lot. So I don't trust it anymore :sweat_smile:

**Comment by vanlummelhuizen** [comment]
@susanodd @Jetske Do we know whether this is solved now?

**Comment by susanodd** [comment]
Here, if I try to upload a large file via other media (new server), I get this:

<h1>FileNotFoundError
       at /dictionary/update/othermedia/</h1>
  <pre class="exception_value">[Errno 2] No such file or directory: 'avconv'</pre>
  

Request Method: | POST
-- | --
http://signbank-new.cls.ru.nl/dictionary/update/othermedia/
4.1.7
FileNotFoundError
[Errno 2] No such file or directory: 'avconv'
/usr/lib/python3.10/subprocess.py, line 1845, in _execute_child
signbank.dictionary.update.add_othermedia
/usr/bin/uwsgi
3.10.6
['.',  '',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/var/www/env/lib/python3.10/site-packages']
Thu, 30 Mar 2023 11:57:08 +0200

**Comment by vanlummelhuizen** [comment]
> Here, if I try to upload a large file via other media (new server), I get this:
> # FileNotFoundError at /dictionary/update/othermedia/
> 
> [Errno 2] No such file or directory: 'avconv'

As I did on the test server (https://github.com/Signbank/Global-signbank/issues/891#issuecomment-1479719306) I added `FFMPEG_PROGRAM = "ffmpeg"` to *signbank/settings/server_specific/server_specific.py*. 

@susanodd Can you try and see whether that fixes it?

**Comment by susanodd** [comment]
It seems to upload okay, but there is no image created.

**Comment by susanodd** [comment]
It's the VideoTests.
They don't actually fail. It's only showing the feedback of them. That it's not able to make the png. (As on the live server.) We don't actually explicitly test image creation. (There is an issue for this.)

**Comment by susanodd** [comment]
I recall an issue that suggested making a model for videos GlossImage along the lines of GlossVideo. But I can't find the issue now. I don't recall what I searched on to find it.

**Comment by susanodd** [comment]
This is the current error message that the tests are generating:

```
The test video does not exist in the archive:  /dictionary/protected_media/glossvideo/NGT/th/thisisatemporarytestlemmaidglosstranslation-1.mp4
Uploading the test video.
Video file: /var/www/writable/glossvideo/NGT/th/thisisatemporarytestlemmaidglosstranslation-1.mp4
ffmpeg -v quiet -i /var/www/writable/glossvideo/NGT/th/thisisatemporarytestlemmaidglosstranslation-1.mp4 -ss 0.0 -t 3.06 -filter:v scale=(trunc((iw/(ih/180.000000))/2+0.5))*2:180.000000 -strict experimental -y /var/www/writable/glossvideo/NGT/th/thisisatemporarytestlemmaidglosstranslation-1_small.mp4
Video file: /var/www/writable/glossvideo/NGT/th/thisisatemporarytestlemmaidglosstranslation-1.mp4
ffmpeg -v quiet -i /var/www/writable/glossvideo/NGT/th/thisisatemporarytestlemmaidglosstranslation-1.mp4 -filter:v scale='iw*max(1,sar)':'ih*max(1,1/sar)' /var/www/writable/tmp/signbank-ExtractMiddleFrame/thisisatemporarytestlemmaidglosstranslation-1.mp4-frames/all/frame-%5d.png
convert /var/www/writable/tmp/signbank-ExtractMiddleFrame/thisisatemporarytestlemmaidglosstranslation-1.mp4-frames/middle/thisisatemporarytestlemmaidglosstranslation-1.png -resize x180 /var/www/writable/tmp/signbank-ExtractMiddleFrame/thisisatemporarytestlemmaidglosstranslation-1.mp4-frames/middle/thisisatemporarytestlemmaidglosstranslation-1_320x180.png
IOError:  [Errno 2] No such file or directory: 'convert'
```

The lines "Video file: " are either from extractMiddleFrame.py or resizeVideos.py

**Comment by vanlummelhuizen** [comment]
@susanodd The  command `convert`  was missing. I added it on the live server with `sudo apt install imagemagick` (you may do `sudo apt update` first). Can you whether this helps?

**Comment by susanodd** [comment]
The still image is created now!!
